### ISSUE TITLE
Building with msbuild from command line

### ISSUE THREAD

**Issue by ozeidan** [0xFireball/xamarin-android-linux#3]
Hey, 

first of all, thanks for writing this excellent guide.
I managed to build my app with xabuild and also with msbuild through Rider. I am wondering how to use msbuild from the command line with app signing. Also I saw you were able to use the debugger. I am unable to run the application on my phone via Rider. Can you shed light on how to do this? In rider it says that my program doesn't have an entry point, which makes sense I guess. Also with `Advanced Build Actions -> Package Selected Projects` I get this error: ` /usr/lib/mono/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(631,2): error MSB4018: The "ResolveSdks" task failed unexpectedly. [/home/omar/Trash/working with maps/Android/WorkingWithMaps.Android.csproj]
/usr/lib/mono/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(631,2): error MSB4018: System.InvalidOperationException: Could not determine Android SDK location. Please provide `androidSdkPath`. [/home/omar/Trash/working with maps/Android/WorkingWithMaps.Android.csproj]`

Any hints would be much appreciated.

**Comment by 0xFireball** [comment]
Hi,

As the error says, it cannot find the `androidSdkPath`. If you took my suggested csproj lines, it will attempt to get these out of the `ANDROID_SDK_PATH` environment variable. Rider seems to override this, so check for the Android settings in Rider's settings to set the path there.

As for running on the phone, I used the Edit Configurations > Xamarin.Android and used Debug Configuration and was able to run and debug on my phone. If you're able to build with msbuild from the command line and you set the sdk paths, you should be able to run it in Rider.

Instructions for using it command line with MSBuild are in the readme, check it out.

**Comment by ozeidan** [comment]
Hi, thanks for your answer. I actually got this working pretty nicely.

Now on another project I have following issues:
if I type in `nuget restore` TestApp.sln, it doesn't do anything. In Rider, it lists the nuget packages which the project depends on correctly, but it doesn't download them correctly. It says 'all packages are installed' but I can't find them anywhere. When running msbuild I get following errors: https://pastebin.com/7nniAzD7

The lower 2 errors are prompting me to restore with nuget. 

What am I missing here? Thanks again for your help

**Comment by 0xFireball** [comment]
This stands out to me:
```
error MSB3644: The reference assemblies for framework "MonoAndroid,Version=v1.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. 
```

it seems that the build isn't finding the MonoAndroid target framework. Can you verify that `MonoAndroid` is present in `/usr/lib/mono/xbuild-frameworks`, and that you are setting `TargetFrameworkRootPath` for msbuild as described in the guide?

**Comment by ozeidan** [comment]
You were right, I actually did this first and forgot to do it again when I set the repo up again.
But now I am getting the error which I actually was talking about:

```
"/home/omar/projects/XamarinTest/TestApp/TestApp/TestApp.Android/TestApp.Android.csproj" (default target) (1) ->
"/home/omar/projects/XamarinTest/TestApp/TestApp/TestApp/TestApp.csproj" (default target) (2:2) ->
(ReportAssetsLogMessages target) -> 
  /usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(327,5): error : Die Ressourcendatei "/home/omar/projects/XamarinTest/TestApp/TestApp/TestApp/obj/project.assets.json" wurde nicht gefunden. Führen Sie eine NuGet-Paketwiederherstellung aus, um diese Datei zu generieren. [/home/omar/projects/XamarinTest/TestApp/TestApp/TestApp/TestApp.csproj]
```


It says project.assets.json not found, run the nuget package restoration to generate this file.

**Comment by 0xFireball** [comment]
I'm not sure about this, but try `dotnet restore`?

**Comment by 0xFireball** [comment]
If that doesn't work, can you make a repro and send it to me so I can take a look?

**Comment by ozeidan** [comment]
I didn't know about dotnet yet, I tried to use `nuget restore` but it doesn't seem to do anything. Specifically it is looking for Xamarin.GooglePlayServices.Basement.

Sure, this is the repo that I am trying to build: https://github.com/fhnaseer/XamarinTest.git

**Comment by ozeidan** [comment]
I got a little bit further. I am encountering this error now:
https://pastebin.com/qxdCdt44
I remember that I got past this once but forgot how. Do you know how to fix this?

**Comment by 0xFireball** [comment]
See this: https://forums.xamarin.com/discussion/59017/no-resource-found-that-matches-the-given-name-theme-appcompat-light

**Comment by 0xFireball** [comment]
@ozeidan is it resolved then?
