### ISSUE TITLE
Could not determine Android SDK location. Please provide `androidSdkPath`.

### ISSUE THREAD

**Issue by Florin-Birgu** [0xFireball/xamarin-android-linux#5]
Hello,
I followed the steps for Rider on my Linux Mint(18.2) machine but with no luck. I am able to compile from the console even with the xbuild command but not inside rider where I get this error:
`  Xamarin.Android.Common.targets: [null] /usr/lib/mono/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: error : Error executing task ResolveSdks: Could not determine Android SDK location. Please provide `androidSdkPath`.`

Thanks for the guides you provided, using Xamarin in Linux is something I wanted to do for a long time.

**Comment by 0xFireball** [comment]
See the instructions:

> Finally, there's one last trick Rider has: it will provide its own Android SDK path by default. To fix that, go into Rider's settings and change the path to the Android SDK in its options.

**Comment by Florin-Birgu** [comment]
Did that and still no luck.

**Comment by 0xFireball** [comment]
Have you tried building with `msbuild`? Setting the `ANDROID_SDK_PATH` environment variable as described?

**Comment by Florin-Birgu** [comment]
After installing `mono-complete` I was able to find the msbuild option. Thanks a lot!

`sudo apt-get install mono-complete`

**Comment by 0xFireball** [comment]
Great, glad to hear that it's resolved.
